export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST';
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS';
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL';

export const BOOK_DETAILS_REQUEST = 'BOOK_DETAILS_REQUEST';
export const BOOK_DETAILS_SUCCESS = 'BOOK_DETAILS_SUCCESS';
export const BOOK_DETAILS_FAIL = 'BOOK_DETAILS_FAIL';

export const BOOK_SAVE_REQUEST = 'BOOK_SAVE_REQUEST';
export const BOOK_SAVE_SUCCESS = 'BOOK_SAVE_SUCCESS';
export const BOOK_SAVE_FAIL = 'BOOK_SAVE_FAIL';

export const BOOK_DELETE_REQUEST = 'BOOK_DELETE_REQUEST';
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS';
export const BOOK_DELETE_FAIL = 'BOOK_DELETE_FAIL';

export const BOOK_REVIEW_SAVE_REQUEST = 'BOOK_REVIEW_SAVE_REQUEST';
export const BOOK_REVIEW_SAVE_SUCCESS = 'BOOK_REVIEW_SAVE_SUCCESS';
export const BOOK_REVIEW_SAVE_FAIL = 'BOOK_REVIEW_SAVE_FAIL';
export const BOOK_REVIEW_SAVE_RESET = 'BOOK_REVIEW_SAVE_RESET';
